version: '3.7'

services:
  httpbin1:
    image: kennethreitz/httpbin
    container_name: httpbin1
    ports:
      - "8081:80"

  httpbin2:
    image: kennethreitz/httpbin
    container_name: httpbin2
    ports:
      - "8082:80"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - httpbin1
      - httpbin2
